node {
    def app

    stage('Clone repository') {
        checkout scm
    }

    stage('Update Git') {
        script {
            catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                withCredentials([usernamePassword(credentialsId: 'github', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                    //def encodedPassword = URLEncoder.encode("$GIT_PASSWORD",'UTF-8')
                    sh "git config user.email samadi130@gmail.com"
                    sh "git config user.name SamaDevOps"
                    //sh "git switch master"
                    sh "cat Jenkins/saha-rajdeep-lab1/deployment/Deployment.yaml"
                    sh "sed -i 's+samadhi995/jenkinspipeline.*+samadhi995/jenkinspipeline:${DOCKERTAG}+g' Jenkins/saha-rajdeep-lab1/deployment/Deployment.yaml"
                    sh "cat Jenkins/saha-rajdeep-lab1/deployment/Deployment.yaml"
                    sh "git add ."
                    sh "git commit -m 'Done by Jenkins Job changemanifest: ${env.BUILD_NUMBER}'"
                    sh "git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/${GIT_USERNAME}/DevOps-Projects.git HEAD:main"
                }
            }                    
        }
    }
}